### PR TITLE
Allow setting the role name

### PR DESCRIPTION
**Pull request by nunofernandes**
This patch allows for the role name to be set to some value. This helps
in scenarios where we are importing already pre-existing resources to
terraform.

### CODE REVIEW

**Comment by eeeady** [comment]
Thank you for submitting this PR @nunofernandes!

This is a good idea but your suggested change would mean you would have to import in the existing role to the backend or you might accidentally create a duplicate named role. I guess that's what you're intending.

Is there a way to make this safer?

**Comment by dynamike** [comment]
This has the potential added benefit of allowing parallelization in our terratests. I'll try looking at this today.

**Comment by dynamike** [comment]
@nunofernandes can you enable maintainer edits on this PR? I've got some changes I'd like to push up. See https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by nunofernandes** [comment]
Hi there,

Reading that, we have:

image

This PR already seems to have the necessary permissions:

image

P.S. - I forked this repo and did the commit on my master branch. As it was a small patch I didn't bother to create a branch from master on my repo

**Comment by dynamike** [comment]
yeah, no dice. It may be because of some master branch protection stuff going on from the forked repo

**Comment by dynamike** [comment]
I'm going to circle back and make a new PR on this

**Comment by dynamike** [comment]
Merged with https://github.com/trussworks/terraform-aws-cloudtrail/pull/126 . Notes the variable name is different

**Pull request closed without merging**
