### PR TITLE
Additional KMS encryption support

### PR DESCRIPTION
**Pull request by jasonmcintosh**

### CODE REVIEW

**Comment by dynamike** [comment]
Thanks for the PR. Can you talk a little bit more about the use case you're trying to address with this PR? Why would you need to grant access to the KMS key to another AWS account?

**Comment by jasonmcintosh** [comment]
Use cases:
* Using an external collector via a trust relationship to collect logs (aka SumoLogic)
* Being able to read the files directly from S3 vs. cloudtrail.  Aka the KMS encryption policies by default ONLY allow reading via cloudtrail, not directly against the S3 bucket
* Being able to grant a non-root/org account federated access for the log entries for off-line storage
* Being able to adjust any other permissions to match policies

The main interest is the second above - reading the logs and feeding to an external entity for analytics purposes.  The current KMS keys do NOT allow direct access via S3 to read the bucket entries.

**Comment by dynamike** [comment]
Thanks for the response. Rather than support blanket IAM policies for the KMS key, couldn't you just modify the [Enable cross account log decryption](https://github.com/trussworks/terraform-aws-cloudtrail/blob/main/main.tf#L179) IAM policy to include multiple [AWS account ids](https://github.com/trussworks/terraform-aws-cloudtrail/blob/main/main.tf#L196)?

**Comment by jasonmcintosh** [comment]
Yes I could, but not:
```
    condition {
      test     = "StringEquals"
      variable = "kms:CallerAccount"
      values   = [data.aws_caller_identity.current.account_id]
    }

    condition {
      test     = "StringLike"
      variable = "kms:EncryptionContext:aws:cloudtrail:arn"
      values   = ["arn:${data.aws_partition.current.partition}:cloudtrail:*:${data.aws_caller_identity.current.account_id}:trail/*"]
    }
```

This would prevent a simple
```
aws s3 cp s3://<bucket>...
```
file from being utilized as it won't have the encryption context.  Again, it's more about enabling flexibility for other types of grants.  IF needed.

**Review by dynamike — COMMENTED** [review]
I'm working on testing this functionality using the example you've provided and keep hitting this error. 
```
Error: error creating KMS Key: MalformedPolicyDocumentException: Policy contains a statement with one or more invalid principals.
```

This is how I set the custom policy

```hcl
  custom_kms_key_access = [                                                                                                                                                       
    {                                                                                                                                                                             
      sid    = "AllowSomeOtherDecryption"                                                                                                                                         
      effect = "Allow"                                                                                                                                                            
      principals = [                                                                                                                                                              
        {                                                                                                                                                                         
          type = "AWS"                                                                                                                                                            
          identifiers = [                                                                                                                                                         
            "arn:aws:iam::123456789012:root"                                                                                                                                      
          ]                                                                                                                                                                       
        }                                                                                                                                                                         
      ]                                                                                                                                                                           
      actions = [                                                                                                                                                                 
        "kms:Decrypt*"                                                                                                                                                            
      ]                                                                                                                                                                           
    }                                                                                                                                                                             
  ]  
```

Any thoughts on what I'm missing?

**Comment by jasonmcintosh** [comment]
The tests on why you need this:

WITHOUT the custom access,
```aws s3 cp s3://blah/blah/file.gz``` where that's an actual encrypted file on the bucket won't work on any of the AWS accounts.

WITH the the above policy the aws s3 cp command will work.  Just pick the account id for your use case.  OR pick a public one if you'd prefer (aka one of the AWS ones might be valid for a 'test' purpose, aka 454464851268 or  similar kinda things, borrowed from https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-supported-regions.html).    

```  custom_kms_key_access = [
    {
      effect = "Allow"
      principals = [ {
          type = "AWS"
          identifiers = [ "475085895292"]
        } ]
      actions = [ "kms:Decrypt*", ]
    }
  ]```

This doesn't have the full ARN - SUPPOSEDLY both work, though that depends on the AWS resource.  To grant to a role it'd be the full ARN (or a canonical one I'd GUESS)

**Comment by dynamike** [comment]
With the account id(1234567890121) or the account id ARN (arn:aws:iam::123456789012:root) I still get the following error on terraform apply

```
Error: error creating KMS Key: MalformedPolicyDocumentException: Policy contains a statement with one or more invalid principals.
```

**Pull request closed without merging**
